[package]
name = "vellogd-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
vellogd-shared = { workspace = true, features = ["use_winit"] }
vello.workspace = true
ipc-channel.workspace = true
