# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib vellogd, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}


`vellogd_impl` <- function(`filename`, `width`, `height`) {
  invisible(.Call(savvy_vellogd_impl__impl, `filename`, `width`, `height`))
}


`save_as_png` <- function(`filename`) {
  invisible(.Call(savvy_save_as_png__impl, `filename`))
}


`dump_patterns` <- function() {
  invisible(.Call(savvy_dump_patterns__impl))
}


`vellogd_with_server_impl` <- function(`filename`, `width`, `height`, `server` = NULL) {
  invisible(.Call(savvy_vellogd_with_server_impl__impl, `filename`, `width`, `height`, `server`))
}


`debuggd` <- function() {
  invisible(.Call(savvy_debuggd__impl))
}


`do_tracing` <- function(`expr`) {
  invisible(.Call(savvy_do_tracing__impl, `expr`))
}


