# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

name: build server

permissions: read-all

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    
    name: "${{ matrix.config.os }}"

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest}
          - {os: macOS-latest  }
          - {os: ubuntu-latest }

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        if: github.ref_type != 'tag'
        with:
          workspaces: src/rust
          shared-key: shared-cache

      - name: Build Rust server
        run: |
          cargo version
          if [ "${{ github.ref_type }}" == 'tag' ]; then
            PROFILE=release
          else
            PROFILE=dev
          fi
          cargo build --profile ${PROFILE} --manifest-path ./src/rust/Cargo.toml -p vellogd-server
        shell: bash

      - uses: actions/upload-artifact@v4
        if: github.ref_type == 'tag'
        with:
          name: server-${{ runner.os }}-${{ runner.arch }}
          path: |
            ./src/rust/target/release/vellogd_server
            ./src/rust/target/release/vellogd_server.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref_type == 'tag'
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        path: artifacts/
        pattern: server-*

    - name: release
      run: |
        mkdir "${{ runner.temp }}/dist/"
        for d in $(ls ./artifacts/); do
          echo "./artifacts/${d}"
          
          cd "./artifacts/${d}"
          chmod +x ./vellogd_server*
          tar -czf "${{ runner.temp }}/dist/${d}.tar.gz" ./vellogd_server*
          cd -
        done

        gh release create ${{ github.ref_name }} ${{ runner.temp }}/dist/*
